openapi: 3.0.0
info:
  version: 0.0.1
  title: Roboflow API
  description: >-
    The Roboflow API
  license:
    url: https://opensource.org/licenses/MIT
    name: MIT
servers:
  - url: /api/v1
security: []
paths:
  /qr-locations:
    $ref: "./paths/qr_location/qr-locations.yml"
  /qr-locations/{qrLocationId}:
    $ref: "./paths/qr_location/qr-locations@{qrLocationId}.yml"

  /raybots:
    $ref: "./paths/raybot/raybots.yml"
  /raybots/{raybotId}:
    $ref: "./paths/raybot/raybots@{raybotId}.yml"

  /raybots/{raybotId}/commands:
    $ref: "./paths/raybot_command/raybots@{raybotId}@commands.yml"
  /raybot-commands/{raybotCommandId}:
    $ref: "./paths/raybot_command/raybot-commands@{raybotCommandId}.yml"

  /workflows:
    $ref: "./paths/workflow/workflows.yml"
  /workflows/{workflowId}:
    $ref: "./paths/workflow/workflows@{workflowId}.yml"
  /workflows/{workflowId}/run:
    $ref: "./paths/workflow/workflows@{workflowId}@run.yml"

  /workflows/{workflowId}/executions:
    $ref: "./paths/workflow_execution/workflows@{workflowId}@executions.yml"
  /workflow-executions/{workflowExecutionId}:
    $ref: "./paths/workflow_execution/workflow-executions@{workflowExecutionId}.yml"
  # /workflow-executions/{workflowExecutionId}/status:
  #   $ref: "./paths/workflow_execution/workflow-executions@{workflowExecutionId}@status.yml"

  /workflow-executions/{workflowExecutionId}/steps:
    $ref: "./paths/step_execution/workflow-executions@{workflowExecutionId}@steps.yml"
  /step-executions/{stepExecutionId}:
    $ref: "./paths/step_execution/step-executions@{stepExecutionId}.yml"
