openapi: 3.0.3
info:
  version: 0.0.1
  title: Roboflow API
  description: >-
    Roboflow API Swagger
  license:
    name: MIT
servers:
  - url: /api
tags:
  - name: raybot
    description: Raybot operations
paths:
  /raybots:
    $ref: "./raybot/raybots.yml"
  /raybots/{raybotId}:
    $ref: "./raybot/raybots@{raybotId}.yml"

  /raybots/{raybotId}/commands:
    $ref: "./raybot_command/raybots@{raybotId}@commands.yml"
  /raybot-commands/{raybotCommandId}:
    $ref: "./raybot_command/raybotCommands@{raybotCommandId}.yml"

  /qr-locations:
    $ref: "./qr_location/qrLocations.yml"
  /qr-locations/{qrLocationId}:
    $ref: "./qr_location/qrLocations@{qrLocationId}.yml"
  # /workflows:
  #   $ref: "./paths/workflows.yml"
  # /workflows/{workflowId}:
  #   $ref: "./paths/workflows@{workflowId}.yml"
