x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "3"

networks:
  roboflow:
    driver: bridge

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - roboflow

  roboflow:
    build:
      context: .
      dockerfile: ./docker/roboflow/server.dockerfile
      target: dev
    container_name: roboflow
    restart: unless-stopped
    volumes:
      - .air.toml:/app/.air.toml
      - ./cmd:/app/cmd
      - ./internal:/app/internal
      - ./pkg:/app/pkg
      - ./bin/oas:/app/bin/oas
      - ./embedded.go:/app/embedded.go
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
    ports:
      - 8080:8080
    environment:
      - HTTP_SERVER_PORT=8080
      - LOG_FORMAT=json
      - LOG_LEVEL=debug
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_SSLMODE=disable
      - NATS_ENABLE_LOG=true
    logging: *logging
    networks:
      - roboflow
    depends_on:
      - postgres
