networks:
  roboflow:
    driver: bridge

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - roboflow

  roboflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roboflow
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - ENV=development
      - PORT=8080
      - POSTGRES_DSN=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres
    networks:
      - roboflow
