// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcpg

import (
	"encoding/json"
	"time"
)

type QrLocation struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	QrCode    string          `json:"qr_code"`
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type Raybot struct {
	ID              string     `json:"id"`
	Name            string     `json:"name"`
	ControlMode     string     `json:"control_mode"`
	IsOnline        bool       `json:"is_online"`
	IpAddress       *string    `json:"ip_address"`
	LastConnectedAt *time.Time `json:"last_connected_at"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

type RaybotCommand struct {
	ID          string          `json:"id"`
	RaybotID    string          `json:"raybot_id"`
	Type        string          `json:"type"`
	Status      string          `json:"status"`
	Inputs      json.RawMessage `json:"inputs"`
	Outputs     json.RawMessage `json:"outputs"`
	Error       *string         `json:"error"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	CompletedAt *time.Time      `json:"completed_at"`
}

type StepExecution struct {
	ID                  string          `json:"id"`
	WorkflowExecutionID string          `json:"workflow_execution_id"`
	Status              string          `json:"status"`
	Node                json.RawMessage `json:"node"`
	Inputs              json.RawMessage `json:"inputs"`
	Outputs             json.RawMessage `json:"outputs"`
	Error               *string         `json:"error"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
	StartedAt           *time.Time      `json:"started_at"`
	CompletedAt         *time.Time      `json:"completed_at"`
}

type Workflow struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	IsDraft     bool            `json:"is_draft"`
	IsValid     bool            `json:"is_valid"`
	Data        json.RawMessage `json:"data"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type WorkflowExecution struct {
	ID          string          `json:"id"`
	WorkflowID  string          `json:"workflow_id"`
	Status      string          `json:"status"`
	Data        json.RawMessage `json:"data"`
	Inputs      json.RawMessage `json:"inputs"`
	Outputs     json.RawMessage `json:"outputs"`
	Error       *string         `json:"error"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	StartedAt   *time.Time      `json:"started_at"`
	CompletedAt *time.Time      `json:"completed_at"`
}
