parameters:
  WorkflowId:
    name: workflowId
    description: The ID of the workflow
    in: path
    required: true
    schema:
      type: string
      format: uuid

schemas:
  WorkflowResponse:
    type: object
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
      description:
        type: string
        nullable: true
      definition:
        $ref: "#/schemas/WorkflowDefinition"
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
    required:
      - id
      - name
      - description
      - createdAt
      - updatedAt
  PagingWorkflowResponse:
    type: object
    properties:
      totalItems:
        type: integer
        format: int64
      items:
        type: array
        items:
          $ref: "#/schemas/PagingWorkflowItemResponse"
    required:
      - totalItems
      - items
  PagingWorkflowItemResponse:
    type: object
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
      description:
        type: string
        nullable: true
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
    required:
    - id
    - name
    - description
    - createdAt
    - updatedAt
  RunWorkflowResponse:
    type: object
    properties:
      workflowExecutionId:
        type: string
        format: uuid
    required:
      - workflowExecutionId
  RunWorkflowRequest:
    type: object
    properties:
      env:
        type: object
        additionalProperties:
          type: string
        x-go-type: map[string]string
    required:
      - env
  CreateWorkflowRequest:
    type: object
    properties:
      name:
        type: string
        minLength: 1
        maxLength: 100
        pattern: "^[a-zA-Z0-9 ]+$"
        example: "my workflow"
      description:
        type: string
        maxLength: 1000
        nullable: true
      definition:
        $ref: "#/schemas/WorkflowDefinition"
    required:
      - name
      - description
      - definition
  UpdateWorkflowRequest:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
        nullable: true
      definition:
        $ref: "#/schemas/WorkflowDefinition"
    required:
      - name
      - description
      - definition

  WorkflowDefinition:
    type: object
    properties:
      nodes:
        type: array
        items:
          $ref: "#/schemas/WorkflowNode"
      edges:
        type: array
        items:
          $ref: "#/schemas/WorkflowEdge"
      viewport:
        $ref: "#/schemas/ViewPort"
      position:
        type: array
        items:
          type: number
          format: float
      zoom:
        type: number
        format: float
    required:
      - nodes
      - edges
      - position
      - viewport
      - zoom
      - env
  WorkflowNode:
    type: object
    properties:
      id:
        type: string
      type:
        $ref: "#/schemas/NodeType"
      initialized:
        type: boolean
      position:
        $ref: "#/schemas/Position"
      definition:
        $ref: "#/schemas/NodeDefinition"
    required:
      - id
      - type
      - initialized
      - position
      - definition
  NodeDefinition:
    type: object
    properties:
      type:
        $ref: "#/schemas/TaskType"
      timeoutSec:
        type: integer
        format: uint16
      fields:
        type: object
        additionalProperties:
          $ref: "#/schemas/NodeField"
    required:
      - type
      - timeoutSec
      - fields
  NodeField:
    type: object
    properties:
      useEnv:
        type: boolean
      key:
        type: string
        nullable: true
      value:
        type: string
        nullable: true
    required:
      - useEnv
      - key
      - value
  NodeType:
    type: string
    enum:
      - RoboflowNode
    x-go-type: string
  TaskType:
    type: string
    enum:
      - VALIDATE
      - STOP
      - MOVE_FORWARD
      - MOVE_BACKWARD
      - MOVE_TO_LOCATION
      - OPEN_BOX
      - CLOSE_BOX
      - LIFT_BOX
      - DROP_BOX
      - CHECK_QR
      - WAIT_GET_ITEM
    x-go-type: string
  WorkflowEdge:
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      source:
        type: string
      target:
        type: string
      sourceHandle:
        type: string
      targetHandle:
        type: string
      label:
        type: string
      animated:
        type: boolean
      sourceX:
        type: number
        format: float
      sourceY:
        type: number
        format: float
      targetX:
        type: number
        format: float
      targetY:
        type: number
        format: float
    required:
      - id
      - type
      - source
      - target
      - sourceHandle
      - targetHandle
      - label
      - animated
      - sourceX
      - sourceY
      - targetX
      - targetY
  ViewPort:
    type: object
    properties:
      x:
        type: number
        format: float
      y:
        type: number
        format: float
      zoom:
        type: number
        format: float
    required:
      - x
      - y
      - zoom
  Position:
    type: object
    properties:
      x:
        type: number
        format: float
      y:
        type: number
        format: float
    required:
      - x
      - y

