// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBulkInsertSteps implements pgx.CopyFromSource.
type iteratorForBulkInsertSteps struct {
	rows                 []BulkInsertStepsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertSteps) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertSteps) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].WorkflowExecutionID,
		r.rows[0].Env,
		r.rows[0].Node,
		r.rows[0].Status,
	}, nil
}

func (r iteratorForBulkInsertSteps) Err() error {
	return nil
}

func (q *Queries) BulkInsertSteps(ctx context.Context, arg []BulkInsertStepsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"steps"}, []string{"id", "workflow_execution_id", "env", "node", "status"}, &iteratorForBulkInsertSteps{rows: arg})
}
