// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: qr_location.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createQRLocation = `-- name: CreateQRLocation :exec
INSERT INTO qr_locations (
    id,
    name,
    qr_code,
    created_at,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateQRLocationParams struct {
	ID        uuid.UUID
	Name      string
	QrCode    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateQRLocation(ctx context.Context, arg CreateQRLocationParams) error {
	_, err := q.db.Exec(ctx, createQRLocation,
		arg.ID,
		arg.Name,
		arg.QrCode,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteQRLocation = `-- name: DeleteQRLocation :exec
DELETE FROM qr_locations
WHERE id = $1
`

func (q *Queries) DeleteQRLocation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQRLocation, id)
	return err
}

const getQRLocation = `-- name: GetQRLocation :one
SELECT id, name, qr_code, created_at, updated_at FROM qr_locations
WHERE id = $1
`

func (q *Queries) GetQRLocation(ctx context.Context, id uuid.UUID) (*QrLocation, error) {
	row := q.db.QueryRow(ctx, getQRLocation, id)
	var i QrLocation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.QrCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listQRLocations = `-- name: ListQRLocations :many
SELECT id, name, qr_code, created_at, updated_at FROM qr_locations
ORDER BY created_at DESC
`

func (q *Queries) ListQRLocations(ctx context.Context) ([]*QrLocation, error) {
	rows, err := q.db.Query(ctx, listQRLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*QrLocation{}
	for rows.Next() {
		var i QrLocation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.QrCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQRLocation = `-- name: UpdateQRLocation :exec
UPDATE qr_locations
SET name = $1,
    qr_code = $2,
    updated_at = $3
WHERE id = $4
`

type UpdateQRLocationParams struct {
	Name      string
	QrCode    string
	UpdatedAt pgtype.Timestamptz
	ID        uuid.UUID
}

func (q *Queries) UpdateQRLocation(ctx context.Context, arg UpdateQRLocationParams) error {
	_, err := q.db.Exec(ctx, updateQRLocation,
		arg.Name,
		arg.QrCode,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
