server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "roboflow-logs"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: "container_name"
      - source_labels: [__meta_docker_container_name]
        target_label: "job"
        replacement: "roboflow"
      - source_labels: [__meta_docker_container_name]
        target_label: "__path__"
        replacement: "/var/log/docker/containers/*$1-json.log"
