// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/tuanvumaihuynh/roboflow/internal/model"

	paging "github.com/tuanvumaihuynh/roboflow/pkg/paging"

	uuid "github.com/google/uuid"

	xsort "github.com/tuanvumaihuynh/roboflow/pkg/xsort"
)

// FakeWorkflowExecutionRepository is an autogenerated mock type for the WorkflowExecutionRepository type
type FakeWorkflowExecutionRepository struct {
	mock.Mock
}

type FakeWorkflowExecutionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *FakeWorkflowExecutionRepository) EXPECT() *FakeWorkflowExecutionRepository_Expecter {
	return &FakeWorkflowExecutionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, workflowExecution
func (_m *FakeWorkflowExecutionRepository) Create(ctx context.Context, workflowExecution model.WorkflowExecution) error {
	ret := _m.Called(ctx, workflowExecution)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.WorkflowExecution) error); ok {
		r0 = rf(ctx, workflowExecution)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FakeWorkflowExecutionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type FakeWorkflowExecutionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - workflowExecution model.WorkflowExecution
func (_e *FakeWorkflowExecutionRepository_Expecter) Create(ctx interface{}, workflowExecution interface{}) *FakeWorkflowExecutionRepository_Create_Call {
	return &FakeWorkflowExecutionRepository_Create_Call{Call: _e.mock.On("Create", ctx, workflowExecution)}
}

func (_c *FakeWorkflowExecutionRepository_Create_Call) Run(run func(ctx context.Context, workflowExecution model.WorkflowExecution)) *FakeWorkflowExecutionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.WorkflowExecution))
	})
	return _c
}

func (_c *FakeWorkflowExecutionRepository_Create_Call) Return(_a0 error) *FakeWorkflowExecutionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FakeWorkflowExecutionRepository_Create_Call) RunAndReturn(run func(context.Context, model.WorkflowExecution) error) *FakeWorkflowExecutionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *FakeWorkflowExecutionRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FakeWorkflowExecutionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type FakeWorkflowExecutionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *FakeWorkflowExecutionRepository_Expecter) Delete(ctx interface{}, id interface{}) *FakeWorkflowExecutionRepository_Delete_Call {
	return &FakeWorkflowExecutionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *FakeWorkflowExecutionRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *FakeWorkflowExecutionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *FakeWorkflowExecutionRepository_Delete_Call) Return(_a0 error) *FakeWorkflowExecutionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FakeWorkflowExecutionRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *FakeWorkflowExecutionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *FakeWorkflowExecutionRepository) Get(ctx context.Context, id uuid.UUID) (model.WorkflowExecution, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.WorkflowExecution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.WorkflowExecution, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.WorkflowExecution); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.WorkflowExecution)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FakeWorkflowExecutionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type FakeWorkflowExecutionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *FakeWorkflowExecutionRepository_Expecter) Get(ctx interface{}, id interface{}) *FakeWorkflowExecutionRepository_Get_Call {
	return &FakeWorkflowExecutionRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *FakeWorkflowExecutionRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *FakeWorkflowExecutionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *FakeWorkflowExecutionRepository_Get_Call) Return(_a0 model.WorkflowExecution, _a1 error) *FakeWorkflowExecutionRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FakeWorkflowExecutionRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.WorkflowExecution, error)) *FakeWorkflowExecutionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function with given fields: ctx, id
func (_m *FakeWorkflowExecutionRepository) GetStatus(ctx context.Context, id uuid.UUID) (model.WorkflowExecutionStatus, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 model.WorkflowExecutionStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.WorkflowExecutionStatus, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.WorkflowExecutionStatus); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.WorkflowExecutionStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FakeWorkflowExecutionRepository_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type FakeWorkflowExecutionRepository_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *FakeWorkflowExecutionRepository_Expecter) GetStatus(ctx interface{}, id interface{}) *FakeWorkflowExecutionRepository_GetStatus_Call {
	return &FakeWorkflowExecutionRepository_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx, id)}
}

func (_c *FakeWorkflowExecutionRepository_GetStatus_Call) Run(run func(ctx context.Context, id uuid.UUID)) *FakeWorkflowExecutionRepository_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *FakeWorkflowExecutionRepository_GetStatus_Call) Return(_a0 model.WorkflowExecutionStatus, _a1 error) *FakeWorkflowExecutionRepository_GetStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FakeWorkflowExecutionRepository_GetStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.WorkflowExecutionStatus, error)) *FakeWorkflowExecutionRepository_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, workflowID, p, sorts
func (_m *FakeWorkflowExecutionRepository) List(ctx context.Context, workflowID uuid.UUID, p paging.Params, sorts []xsort.Sort) (*paging.List[model.WorkflowExecution], error) {
	ret := _m.Called(ctx, workflowID, p, sorts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *paging.List[model.WorkflowExecution]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, paging.Params, []xsort.Sort) (*paging.List[model.WorkflowExecution], error)); ok {
		return rf(ctx, workflowID, p, sorts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, paging.Params, []xsort.Sort) *paging.List[model.WorkflowExecution]); ok {
		r0 = rf(ctx, workflowID, p, sorts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paging.List[model.WorkflowExecution])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, paging.Params, []xsort.Sort) error); ok {
		r1 = rf(ctx, workflowID, p, sorts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FakeWorkflowExecutionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type FakeWorkflowExecutionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - workflowID uuid.UUID
//   - p paging.Params
//   - sorts []xsort.Sort
func (_e *FakeWorkflowExecutionRepository_Expecter) List(ctx interface{}, workflowID interface{}, p interface{}, sorts interface{}) *FakeWorkflowExecutionRepository_List_Call {
	return &FakeWorkflowExecutionRepository_List_Call{Call: _e.mock.On("List", ctx, workflowID, p, sorts)}
}

func (_c *FakeWorkflowExecutionRepository_List_Call) Run(run func(ctx context.Context, workflowID uuid.UUID, p paging.Params, sorts []xsort.Sort)) *FakeWorkflowExecutionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(paging.Params), args[3].([]xsort.Sort))
	})
	return _c
}

func (_c *FakeWorkflowExecutionRepository_List_Call) Return(_a0 *paging.List[model.WorkflowExecution], _a1 error) *FakeWorkflowExecutionRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FakeWorkflowExecutionRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, paging.Params, []xsort.Sort) (*paging.List[model.WorkflowExecution], error)) *FakeWorkflowExecutionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, workflowExecution
func (_m *FakeWorkflowExecutionRepository) Update(ctx context.Context, workflowExecution model.WorkflowExecution) (model.WorkflowExecution, error) {
	ret := _m.Called(ctx, workflowExecution)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.WorkflowExecution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.WorkflowExecution) (model.WorkflowExecution, error)); ok {
		return rf(ctx, workflowExecution)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.WorkflowExecution) model.WorkflowExecution); ok {
		r0 = rf(ctx, workflowExecution)
	} else {
		r0 = ret.Get(0).(model.WorkflowExecution)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.WorkflowExecution) error); ok {
		r1 = rf(ctx, workflowExecution)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FakeWorkflowExecutionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type FakeWorkflowExecutionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - workflowExecution model.WorkflowExecution
func (_e *FakeWorkflowExecutionRepository_Expecter) Update(ctx interface{}, workflowExecution interface{}) *FakeWorkflowExecutionRepository_Update_Call {
	return &FakeWorkflowExecutionRepository_Update_Call{Call: _e.mock.On("Update", ctx, workflowExecution)}
}

func (_c *FakeWorkflowExecutionRepository_Update_Call) Run(run func(ctx context.Context, workflowExecution model.WorkflowExecution)) *FakeWorkflowExecutionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.WorkflowExecution))
	})
	return _c
}

func (_c *FakeWorkflowExecutionRepository_Update_Call) Return(_a0 model.WorkflowExecution, _a1 error) *FakeWorkflowExecutionRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FakeWorkflowExecutionRepository_Update_Call) RunAndReturn(run func(context.Context, model.WorkflowExecution) (model.WorkflowExecution, error)) *FakeWorkflowExecutionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewFakeWorkflowExecutionRepository creates a new instance of FakeWorkflowExecutionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFakeWorkflowExecutionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FakeWorkflowExecutionRepository {
	mock := &FakeWorkflowExecutionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
